# Generated by Django 2.1.3 on 2018-11-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('taxa_juro', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('percentual_entrada', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('quantidade_parcelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicial', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
